<a href="https://colab.research.google.com/github/Dhanrajs007/PySpark/blob/main/PySpark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pyspark

Requirement already satisfied: pyspark in /usr/local/lib/python3.12/dist-packages (4.0.2)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /usr/local/lib/python3.12/dist-packages (from pyspark) (0.10.9.9)

## **Reading data using spark (CSV)**
spark.read.format().option("",'').load()

In [10]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName(
    'Read CSV File into DataFrame').getOrCreate()

data = spark.read.csv('/content/sample_data/california_housing_test.csv', sep=',',
                         inferSchema=True, header=True)

df = data.toPandas()
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [11]:
#Porduction reliable code for reading the files
data = spark.read.format('csv').option("header",True) \
          .option("inferSchema",True).option("delimiter",',') \
            .load('/content/sample_data/california_housing_test.csv')

df = data.toPandas()
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

## **Converting RDD (Resilient Distributed Datasets) into Dataframes**
createDataFrame / toDF function

In [20]:
# Creating RDD and converting it into dataset (Object oriented way)

# importing necessary libraries
from pyspark.sql import SparkSession

# function to create new SparkSession
def create_session():
  spk = SparkSession.builder \
      .appName("Corona_cases_statewise.com") \
      .getOrCreate()
  return spk

# function to create RDD
def create_RDD(sc_obj,data):
  df = sc.parallelize(data)
  return df

# function to convert RDD to dataframe
def RDD_to_df(spark,df,schema):

  # converting RDD to df using createDataframe()
  # in which we are passing RDD and schema of df
  df1 = spark.createDataFrame(df,schema)
  return df1

if __name__ == "__main__":

  input_data = [("Uttar Pradesh",122000,89600,12238),
          ("Maharashtra",454000,380000,67985),
          ("Tamil Nadu",115000,102000,13933),
          ("Karnataka",147000,111000,15306),
          ("Kerala",153000,124000,5259)]

  # calling function to create SparkSession
  spark = create_session()

  # creating spark context object
  sc = spark.sparkContext

  # calling function to create RDD
  rd_df = create_RDD(sc,input_data)

  schema_lst = ["State","Cases","Recovered","Deaths"]

  # calling function to convert RDD to dataframe
  converted_df = RDD_to_df(spark,rd_df,schema_lst)

  # visualizing the schema and dataframe
  print(type(rd_df))
  converted_df.printSchema()
  converted_df.show()

<class 'pyspark.core.rdd.RDD'>
root
 |-- State: string (nullable = true)
 |-- Cases: long (nullable = true)
 |-- Recovered: long (nullable = true)
 |-- Deaths: long (nullable = true)

+-------------+------+---------+------+
|        State| Cases|Recovered|Deaths|
+-------------+------+---------+------+
|Uttar Pradesh|122000|    89600| 12238|
|  Maharashtra|454000|   380000| 67985|
|   Tamil Nadu|115000|   102000| 13933|
|    Karnataka|147000|   111000| 15306|
|       Kerala|153000|   124000|  5259|
+-------------+------+---------+------+

In [25]:

data = '/content/sample_data/california_housing_test.csv'

sc = spark.sparkContext

rdd_df = sc.parallelize(data)

print(type(rdd_df))

schema_lst = ["longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","median_house_value"]

converted_rdd_df = spark.createDataFrame(rdd_df,schema_lst)

converted_rdd_df.show()

<class 'pyspark.core.rdd.RDD'>

PySparkTypeError: [CANNOT_INFER_SCHEMA_FOR_TYPE] Can not infer schema for type: `str`.

In [26]:
# Using DF function

# importing necessary libraries
from pyspark.sql import SparkSession

# function to create new SparkSession
def create_session():
  spk = SparkSession.builder \
      .appName("Corona_cases_statewise.com") \
      .getOrCreate()
  return spk

# function to create RDD
def create_RDD(sc,data):
  df = sc.parallelize(data)
  return df

# function to convert RDD to dataframe
def RDD_to_df(df,schema):

  # converting RDD to dataframe using toDF()
  # in which we are passing schema of df
  df = rd_df.toDF(schema)
  return df

if __name__ == "__main__":

  input_data = [("Uttar Pradesh",122000,89600,12238),
          ("Maharashtra",454000,380000,67985),
          ("Tamil Nadu",115000,102000,13933),
          ("Karnataka",147000,111000,15306),
          ("Kerala",153000,124000,5259)]

  # calling function to create SparkSession
  spark = create_session()

  # creating spark context object
  sc = spark.sparkContext

  # calling function to create RDD
  rd_df = create_RDD(sc,input_data)

  schema_lst = ["State","Cases","Recovered","Deaths"]

  # calling function to convert RDD to dataframe
  converted_df = RDD_to_df(rd_df,schema_lst)

  # visualizing the schema and dataframe
  converted_df.printSchema()
  converted_df.show()

root
 |-- State: string (nullable = true)
 |-- Cases: long (nullable = true)
 |-- Recovered: long (nullable = true)
 |-- Deaths: long (nullable = true)

+-------------+------+---------+------+
|        State| Cases|Recovered|Deaths|
+-------------+------+---------+------+
|Uttar Pradesh|122000|    89600| 12238|
|  Maharashtra|454000|   380000| 67985|
|   Tamil Nadu|115000|   102000| 13933|
|    Karnataka|147000|   111000| 15306|
|       Kerala|153000|   124000|  5259|
+-------------+------+---------+------+

## **Creating Pyspark dataframes using multiple lists**

In [1]:
# importing module
import pyspark

# importing sparksession from
# pyspark.sql module
from pyspark.sql import SparkSession

# creating sparksession and giving
# an app name
spark = SparkSession.builder.appName('sparkdf').getOrCreate()

# list  of college data with dictionary
# with four lists in three elements each
data = [1, 2, 3]
data1 = ["sravan", "bobby", "ojaswi"]
data2 = ["iit-k", "iit-mumbai", "vignan university"]
data3 = ["AP", "TS", "UP"]

# specify column names
columns = ['ID', 'NAME', 'COLLEGE', 'ADDRESS']

# creating a dataframe by zipping
# the two lists
dataframe = spark.createDataFrame(
  zip(data, data1, data2, data3), columns)

# show data frame
dataframe.show()

+---+------+-----------------+-------+
| ID|  NAME|          COLLEGE|ADDRESS|
+---+------+-----------------+-------+
|  1|sravan|            iit-k|     AP|
|  2| bobby|       iit-mumbai|     TS|
|  3|ojaswi|vignan university|     UP|
+---+------+-----------------+-------+

## **Creating pyspark dataframe using dictionary**

In [2]:
# importing module
import pyspark

# importing sparksession from
# pyspark.sql module
from pyspark.sql import SparkSession

# creating sparksession and giving
# an app name
spark = SparkSession.builder.appName('sparkdf').getOrCreate()

# list  of college data with  dictionary
# with three  dictionaries
data = [{'student_id': 12, 'name': 'sravan', 'address': 'kakumanu'},
        {'student_id': 14, 'name': 'jyothika', 'address': 'tenali'},
        {'student_id': 11, 'name': 'deepika', 'address': 'repalle'}]

# creating a dataframe
dataframe = spark.createDataFrame(data)

# show data frame
dataframe.show()

+--------+--------+----------+
| address|    name|student_id|
+--------+--------+----------+
|kakumanu|  sravan|        12|
|  tenali|jyothika|        14|
| repalle| deepika|        11|
+--------+--------+----------+

## **Creating dataframe from List of CustomTypes(datatypes)**
We can create custome types using customType class as shown below and the row class to create row objects to be created in the list of objects

In [4]:
## Approach 1 - using multiple lists of custom objects
# Importing required modules
from pyspark.sql import Row
from pyspark.sql import SparkSession

# Create a SparkSession
spark = SparkSession.builder.appName("MyApp").getOrCreate()
# Define a custom class to represent a row in the dataframe
class CustomType:
    def __init__(self, name,
                 age, salary):
        self.name = name
        self.age = age
        self.salary = salary

# Create a list of CustomType objects
data = [CustomType("John", 30, 5000),
        CustomType("Mary", 25, 6000),
        CustomType("Mike", 35, 7000)]

# Convert the list of CustomType
# objects to a list of Row objects
rows = [Row(name=d.name,
            age=d.age,
            salary=d.salary) for d in data]

# Create a dataframe from the list of Row objects
df = spark.createDataFrame(rows)

# Show the dataframe
df.show()

+----+---+------+
|name|age|salary|
+----+---+------+
|John| 30|  5000|
|Mary| 25|  6000|
|Mike| 35|  7000|
+----+---+------+

In [6]:
## Approch 2 - Creating custom types using RDD

from pyspark.sql import Row
from pyspark.sql import SparkSession
# Create a SparkSession
spark = SparkSession.builder.appName("Metadata").getOrCreate()
# Define a custom class to represent a row in the dataframe
class CustomType:
    def __init__(self, name, age, salary):
        self.name = name
        self.age = age
        self.salary = salary

# Create a list of CustomType objects
data = [CustomType("John", 30, 5000),
        CustomType("Mary", 25, 6000),
        CustomType("Mike", 35, 7000)]

rdd = spark.sparkContext.parallelize(data)

# Create a dataframe from the rdd
df = spark.createDataFrame(rdd)

# Show the dataframe
df.show()

+---+----+------+
|age|name|salary|
+---+----+------+
| 30|John|  5000|
| 25|Mary|  6000|
| 35|Mike|  7000|
+---+----+------+

In [1]:
## Approach 3 - Creating the schema using the struct

# Importing required modules
from pyspark.sql import SparkSession
from pyspark.sql.types import StructType, StructField, StringType, IntegerType
from pyspark.sql import Row

# Create a SparkSession
spark = SparkSession.builder.appName("Myapp").getOrCreate()

# step 1: Define the schema for the dataframe
schema = StructType([
    StructField("name",
                StringType(), True),
    StructField("age",
                IntegerType(), True),
    StructField("salary",
                IntegerType(), True)
])

# step 2: Create a list of custom objects
data = [{"name": "John",
         "age": 30, "salary": 5000},
        {"name": "Mary",
         "age": 25, "salary": 6000},
        {"name": "Mike",
         "age": 35, "salary": 7000}]

# step 3: Create the dataframe
df = spark.createDataFrame(data, schema)

# step 4: Show the dataframe
df.show()

+----+---+------+
|name|age|salary|
+----+---+------+
|John| 30|  5000|
|Mary| 25|  6000|
|Mike| 35|  7000|
+----+---+------+

## **Basic Transformations**
Perform transformations like joins, filters and mappings on your datasets.

In [4]:
import pyspark
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('sparkdf').getOrCreate() # Init SparkSession

d = [["1", "sravan", "company 1"],
        ["2", "ojaswi", "company 1"],
        ["3", "rohith", "company 2"],
        ["4", "sridevi", "company 1"],
        ["5", "bobby", "company 1"]]

cols = ['ID', 'Name', 'Company']
df1 = spark.createDataFrame(d, cols)
df1.show()

+---+-------+---------+
| ID|   Name|  Company|
+---+-------+---------+
|  1| sravan|company 1|
|  2| ojaswi|company 1|
|  3| rohith|company 2|
|  4|sridevi|company 1|
|  5|  bobby|company 1|
+---+-------+---------+

In [5]:
import pyspark
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('sparkdf').getOrCreate() # Init SparkSession

d1 = [["1", "45000", "IT"],
         ["2", "145000", "Manager"],
         ["6", "45000", "HR"],
         ["5", "34000", "Sales"]]

cols = ['ID', 'salary', 'department']
df2 = spark.createDataFrame(d1, cols)

df2.show()

+---+------+----------+
| ID|salary|department|
+---+------+----------+
|  1| 45000|        IT|
|  2|145000|   Manager|
|  6| 45000|        HR|
|  5| 34000|     Sales|
+---+------+----------+

In [10]:
#innner join

df1.join(df2, df1.ID == df2.ID,'inner').show()

+---+------+---------+---+------+----------+
| ID|  Name|  Company| ID|salary|department|
+---+------+---------+---+------+----------+
|  1|sravan|company 1|  1| 45000|        IT|
|  2|ojaswi|company 1|  2|145000|   Manager|
|  5| bobby|company 1|  5| 34000|     Sales|
+---+------+---------+---+------+----------+

In [11]:
#Full outer join

# using full keyword
df1.join(df2, df1.ID == df2.ID, 'full').show()

# using fullouter keyword
df1.join(df2, df1.ID == df2.ID, 'fullouter').show()

# using outer keyword
df1.join(df2, df1.ID == df2.ID, 'outer').show()

+----+-------+---------+----+------+----------+
|  ID|   Name|  Company|  ID|salary|department|
+----+-------+---------+----+------+----------+
|   1| sravan|company 1|   1| 45000|        IT|
|   2| ojaswi|company 1|   2|145000|   Manager|
|   3| rohith|company 2|NULL|  NULL|      NULL|
|   4|sridevi|company 1|NULL|  NULL|      NULL|
|   5|  bobby|company 1|   5| 34000|     Sales|
|NULL|   NULL|     NULL|   6| 45000|        HR|
+----+-------+---------+----+------+----------+

+----+-------+---------+----+------+----------+
|  ID|   Name|  Company|  ID|salary|department|
+----+-------+---------+----+------+----------+
|   1| sravan|company 1|   1| 45000|        IT|
|   2| ojaswi|company 1|   2|145000|   Manager|
|   3| rohith|company 2|NULL|  NULL|      NULL|
|   4|sridevi|company 1|NULL|  NULL|      NULL|
|   5|  bobby|company 1|   5| 34000|     Sales|
|NULL|   NULL|     NULL|   6| 45000|        HR|
+----+-------+---------+----+------+----------+

+----+-------+---------+----+------+----------+
|  ID|   Name|  Company|  ID|salary|department|
+----+-------+---------+----+------+----------+
|   1| sravan|company 1|   1| 45000|        IT|
|   2| ojaswi|company 1|   2|145000|   Manager|
|   3| rohith|company 2|NULL|  NULL|      NULL|
|   4|sridevi|company 1|NULL|  NULL|      NULL|
|   5|  bobby|company 1|   5| 34000|     Sales|
|NULL|   NULL|     NULL|   6| 45000|        HR|
+----+-------+---------+----+------+----------+

In [15]:
# left join / left outer

# using left keyword
df1.join(df2, df1.ID == df2.ID, 'left').show()

# using left outer keyword
df1.join(df2, df1.ID == df2.ID, 'leftouter').show()

+---+-------+---------+----+------+----------+
| ID|   Name|  Company|  ID|salary|department|
+---+-------+---------+----+------+----------+
|  1| sravan|company 1|   1| 45000|        IT|
|  2| ojaswi|company 1|   2|145000|   Manager|
|  3| rohith|company 2|NULL|  NULL|      NULL|
|  5|  bobby|company 1|   5| 34000|     Sales|
|  4|sridevi|company 1|NULL|  NULL|      NULL|
+---+-------+---------+----+------+----------+

+---+-------+---------+----+------+----------+
| ID|   Name|  Company|  ID|salary|department|
+---+-------+---------+----+------+----------+
|  1| sravan|company 1|   1| 45000|        IT|
|  2| ojaswi|company 1|   2|145000|   Manager|
|  3| rohith|company 2|NULL|  NULL|      NULL|
|  5|  bobby|company 1|   5| 34000|     Sales|
|  4|sridevi|company 1|NULL|  NULL|      NULL|
+---+-------+---------+----+------+----------+

In [16]:
# Right join / rightouter join

# using right keyword
df1.join(df2, df1.ID == df2.ID, 'right').show()

# using rightouter keyword
df1.join(df2, df1.ID == df2.ID, 'rightouter').show()

+----+------+---------+---+------+----------+
|  ID|  Name|  Company| ID|salary|department|
+----+------+---------+---+------+----------+
|   1|sravan|company 1|  1| 45000|        IT|
|   2|ojaswi|company 1|  2|145000|   Manager|
|   5| bobby|company 1|  5| 34000|     Sales|
|NULL|  NULL|     NULL|  6| 45000|        HR|
+----+------+---------+---+------+----------+

+----+------+---------+---+------+----------+
|  ID|  Name|  Company| ID|salary|department|
+----+------+---------+---+------+----------+
|   1|sravan|company 1|  1| 45000|        IT|
|   2|ojaswi|company 1|  2|145000|   Manager|
|   5| bobby|company 1|  5| 34000|     Sales|
|NULL|  NULL|     NULL|  6| 45000|        HR|
+----+------+---------+---+------+----------+

In [18]:
# left semi - only matching from left

df1.join(df2, df1.ID == df2.ID, 'leftsemi').show()

+---+------+---------+
| ID|  Name|  Company|
+---+------+---------+
|  1|sravan|company 1|
|  2|ojaswi|company 1|
|  5| bobby|company 1|
+---+------+---------+

In [19]:
# left anti - not matching from left

df1.join(df2, df1.ID == df2.ID, 'leftanti').show()

+---+-------+---------+
| ID|   Name|  Company|
+---+-------+---------+
|  3| rohith|company 2|
|  4|sridevi|company 1|
+---+-------+---------+

In [20]:
# Create temp views
df1.createOrReplaceTempView("student")
df2.createOrReplaceTempView("department")

# SQL join on ID
spark.sql("""
    SELECT * FROM student
    JOIN department
    ON student.ID = department.ID
""").show()

+---+------+---------+---+------+----------+
| ID|  Name|  Company| ID|salary|department|
+---+------+---------+---+------+----------+
|  1|sravan|company 1|  1| 45000|        IT|
|  2|ojaswi|company 1|  2|145000|   Manager|
|  5| bobby|company 1|  5| 34000|     Sales|
+---+------+---------+---+------+----------+

In [22]:
# SQL inner join on ID
spark.sql("SELECT * FROM student LEFT JOIN department ON student.ID == department.ID").show()

+---+-------+---------+----+------+----------+
| ID|   Name|  Company|  ID|salary|department|
+---+-------+---------+----+------+----------+
|  1| sravan|company 1|   1| 45000|        IT|
|  2| ojaswi|company 1|   2|145000|   Manager|
|  3| rohith|company 2|NULL|  NULL|      NULL|
|  5|  bobby|company 1|   5| 34000|     Sales|
|  4|sridevi|company 1|NULL|  NULL|      NULL|
+---+-------+---------+----+------+----------+

In [9]:
# Join on multiple columns

# Working with & operation
# Results only matching values from the all the rows / row level matching for given columns in condition

# importing module
import pyspark

# importing sparksession from pyspark.sql module
from pyspark.sql import SparkSession

# creating sparksession and giving an app name
spark = SparkSession.builder.appName('sparkdf').getOrCreate()

# list  of employee data
data = [(1, "sravan"), (2, "ojsawi"), (3, "bobby"), (5,"ganesh")]

# specify column names
columns = ['ID1', 'NAME1']

# creating a dataframe from the lists of data
dataframe = spark.createDataFrame(data, columns)

# dataframe.show()

# importing module
import pyspark

# importing sparksession from pyspark.sql module
from pyspark.sql import SparkSession

# creating sparksession and giving an app name
spark = SparkSession.builder.appName('sparkdf').getOrCreate()

# list  of employee data
data = [(1, "sravan"), (2, "ojsawi"),
        (3, "bobby"),
        (4, "rohith"), (5, "gnanesh")]

# specify column names
columns = ['ID2', 'NAME2']

# creating a dataframe from the lists of data
dataframe1 = spark.createDataFrame(data, columns)

# dataframe1.show()

dataframe.join(dataframe1, (dataframe.ID1 == dataframe1.ID2) & (dataframe.NAME1 == dataframe1.NAME2)).show()

+---+------+---+------+
|ID1| NAME1|ID2| NAME2|
+---+------+---+------+
|  1|sravan|  1|sravan|
|  2|ojsawi|  2|ojsawi|
|  3| bobby|  3| bobby|
+---+------+---+------+

In [10]:
# Multiple columns

# Working with | operator
# Results in if either of the condition is satisfied at row level

dataframe.join(dataframe1, (dataframe.ID1 == dataframe1.ID2) | (dataframe.NAME1 == dataframe1.NAME2)).show()

+---+------+---+-------+
|ID1| NAME1|ID2|  NAME2|
+---+------+---+-------+
|  1|sravan|  1| sravan|
|  2|ojsawi|  2| ojsawi|
|  3| bobby|  3|  bobby|
|  5|ganesh|  5|gnanesh|
+---+------+---+-------+

# **Column Operations**
Add, change, rename columns

In [23]:
# Adding the costant column

# Using lit or sql query

# Create a spark session
from pyspark.sql import SparkSession
from pyspark.sql.functions import lit
spark = SparkSession.builder.appName('SparkExamples').getOrCreate()

# Create a spark dataframe
columns = ["Name", "Course_Name",
           "Months",
           "Course_Fees", "Discount",
           "Start_Date", "Payment_Done"]
data = [
    ("Amit Pathak", "Python", 3,
     10000, 1000, "02-07-2021", True),
    ("Shikhar Mishra", "Soft skills",
     2, 8000, 800, "07-10-2021", False),
    ("Shivani Suvarna", "Accounting", 6,
     15000, 1500, "20-08-2021", True),
    ("Pooja Jain", "Data Science", 12,
     60000, 900, "02-12-2021", False),
]
df = spark.createDataFrame(data).toDF(*columns)

# View the dataframe
df.show()

# Adding a constant column using lit
df.withColumn("Status", lit(2)).show()  # constant value

df1=df.withColumn("Status", lit(2))
# Importing required functions
from pyspark.sql.functions import when, lit, col
df1.withColumn("Course_Status", when(col("Course_Fees") >= 15000,lit("High")) \
              .otherwise(lit("Moderate"))).show()                 # values based on another column

+---------------+------------+------+-----------+--------+----------+------------+
|           Name| Course_Name|Months|Course_Fees|Discount|Start_Date|Payment_Done|
+---------------+------------+------+-----------+--------+----------+------------+
|    Amit Pathak|      Python|     3|      10000|    1000|02-07-2021|        true|
| Shikhar Mishra| Soft skills|     2|       8000|     800|07-10-2021|       false|
|Shivani Suvarna|  Accounting|     6|      15000|    1500|20-08-2021|        true|
|     Pooja Jain|Data Science|    12|      60000|     900|02-12-2021|       false|
+---------------+------------+------+-----------+--------+----------+------------+

+---------------+------------+------+-----------+--------+----------+------------+------+
|           Name| Course_Name|Months|Course_Fees|Discount|Start_Date|Payment_Done|Status|
+---------------+------------+------+-----------+--------+----------+------------+------+
|    Amit Pathak|      Python|     3|      10000|    1000|02-07-2021|        true|     2|
| Shikhar Mishra| Soft skills|     2|       8000|     800|07-10-2021|       false|     2|
|Shivani Suvarna|  Accounting|     6|      15000|    1500|20-08-2021|        true|     2|
|     Pooja Jain|Data Science|    12|      60000|     900|02-12-2021|       false|     2|
+---------------+------------+------+-----------+--------+----------+------------+------+

+---------------+------------+------+-----------+--------+----------+------------+------+-------------+
|           Name| Course_Name|Months|Course_Fees|Discount|Start_Date|Payment_Done|Status|Course_Status|
+---------------+------------+------+-----------+--------+----------+------------+------+-------------+
|    Amit Pathak|      Python|     3|      10000|    1000|02-07-2021|        true|     2|     Moderate|
| Shikhar Mishra| Soft skills|     2|       8000|     800|07-10-2021|       false|     2|     Moderate|
|Shivani Suvarna|  Accounting|     6|      15000|    1500|20-08-2021|        true|     2|         High|
|     Pooja Jain|Data Science|    12|      60000|     900|02-12-2021|       false|     2|         High|
+---------------+------------+------+-----------+--------+----------+------------+------+-------------+

In [25]:
# New constant column using sql query

df.registerTempTable('table')

# df1.registerTempTable('table')

newDF = spark.sql('select *, 1 as newCol from table')
newDF.show()

/usr/local/lib/python3.12/dist-packages/pyspark/sql/classic/dataframe.py:178: FutureWarning: Deprecated in 2.0, use createOrReplaceTempView instead.
  warnings.warn("Deprecated in 2.0, use createOrReplaceTempView instead.", FutureWarning)

+---------------+------------+------+-----------+--------+----------+------------+------+------+
|           Name| Course_Name|Months|Course_Fees|Discount|Start_Date|Payment_Done|Status|newCol|
+---------------+------------+------+-----------+--------+----------+------------+------+------+
|    Amit Pathak|      Python|     3|      10000|    1000|02-07-2021|        true|     2|     1|
| Shikhar Mishra| Soft skills|     2|       8000|     800|07-10-2021|       false|     2|     1|
|Shivani Suvarna|  Accounting|     6|      15000|    1500|20-08-2021|        true|     2|     1|
|     Pooja Jain|Data Science|    12|      60000|     900|02-12-2021|       false|     2|     1|
+---------------+------------+------+-----------+--------+----------+------------+------+------+

In [26]:
# Adding column into dataframe

# importing module
import pyspark

# importing sparksession from pyspark.sql module
from pyspark.sql import SparkSession

# creating sparksession and giving an app name
spark = SparkSession.builder.appName('sparkdf').getOrCreate()

# list  of employee data
data = [["1", "sravan", "company 1"],
        ["2", "ojaswi", "company 1"],
        ["3", "rohith", "company 2"],
        ["4", "sridevi", "company 1"],
        ["5", "bobby", "company 1"]]

# specify column names
columns = ['ID', 'NAME', 'Company']

# creating a dataframe from the lists of data
dataframe = spark.createDataFrame(data, columns)

dataframe.show()

+---+-------+---------+
| ID|   NAME|  Company|
+---+-------+---------+
|  1| sravan|company 1|
|  2| ojaswi|company 1|
|  3| rohith|company 2|
|  4|sridevi|company 1|
|  5|  bobby|company 1|
+---+-------+---------+

In [28]:
# Adding new column - using lit and withColumn

dataframe.withColumn("new_col", lit("1")).show()

+---+-------+---------+-------+
| ID|   NAME|  Company|new_col|
+---+-------+---------+-------+
|  1| sravan|company 1|      1|
|  2| ojaswi|company 1|      1|
|  3| rohith|company 2|      1|
|  4|sridevi|company 1|      1|
|  5|  bobby|company 1|      1|
+---+-------+---------+-------+

In [34]:
# Adding column based on another column in dataframe
from pyspark.sql.functions import col,lit

dataframe.withColumn("new_ID", dataframe.ID*1000).show()

+---+-------+---------+------+
| ID|   NAME|  Company|new_ID|
+---+-------+---------+------+
|  1| sravan|company 1|  1000|
|  2| ojaswi|company 1|  2000|
|  3| rohith|company 2|  3000|
|  4|sridevi|company 1|  4000|
|  5|  bobby|company 1|  5000|
+---+-------+---------+------+

In [36]:
# Adding columns using concating other columns
# concat_ws - concat_ws(seperator,col1,col2,etc)

from pyspark.sql.functions import concat_ws

dataframe.withColumn("emp_name",concat_ws("-",dataframe.NAME,dataframe.Company)).show()

+---+-------+---------+-----------------+
| ID|   NAME|  Company|         emp_name|
+---+-------+---------+-----------------+
|  1| sravan|company 1| sravan-company 1|
|  2| ojaswi|company 1| ojaswi-company 1|
|  3| rohith|company 2| rohith-company 2|
|  4|sridevi|company 1|sridevi-company 1|
|  5|  bobby|company 1|  bobby-company 1|
+---+-------+---------+-----------------+

In [52]:
# Adding column when not exists in dataframe
# using if condition

# importing module
import pyspark

# import concat_ws and lit function
from pyspark.sql.functions import concat_ws, lit

# importing sparksession from pyspark.sql module
from pyspark.sql import SparkSession

# creating sparksession and giving an app name
spark = SparkSession.builder.appName('sparkdf').getOrCreate()

# list  of employee data
data = [["1", "sravan", "company 1"],
        ["2", "ojaswi", "company 1"],
        ["3", "rohith", "company 2"],
        ["4", "sridevi", "company 1"],
        ["5", "bobby", "company 1"]]

# specify column names
columns = ['ID', 'NAME', 'Company']

# creating a dataframe from the lists of data
dataframe = spark.createDataFrame(data, columns)

# add salary column by checking its existence
if 'salary' not in dataframe.columns:
    dataframe.withColumn("salary", lit(34000)).show()

if 'ID' not in dataframe.columns:
    dataframe.withColumn("Status",lit(1)).show()
else:
  dataframe.withColumn("Status",lit(2)).show()

+---+-------+---------+------+
| ID|   NAME|  Company|salary|
+---+-------+---------+------+
|  1| sravan|company 1| 34000|
|  2| ojaswi|company 1| 34000|
|  3| rohith|company 2| 34000|
|  4|sridevi|company 1| 34000|
|  5|  bobby|company 1| 34000|
+---+-------+---------+------+

+---+-------+---------+------+
| ID|   NAME|  Company|Status|
+---+-------+---------+------+
|  1| sravan|company 1|     2|
|  2| ojaswi|company 1|     2|
|  3| rohith|company 2|     2|
|  4|sridevi|company 1|     2|
|  5|  bobby|company 1|     2|
+---+-------+---------+------+

In [76]:
# Adding column using select or select expression

# Select function
dataframe.select(lit("Hi").alias("greetings")).show()

# select expression
# dataframe.createGlobalTempView("dan")
# spark.sql("select '1' as New_col from dan").show()

+---------+
|greetings|
+---------+
|       Hi|
|       Hi|
|       Hi|
|       Hi|
|       Hi|
+---------+

In [92]:
# Adding columm with multiple conditionsc# recheck this why not working
from pyspark.sql.functions import when,lit

dataframe.withColumn("Salary",when(dataframe.ID/2 != 0.0,lit('100000')) \
                     .when((dataframe.ID/2 != 0.0) & (dataframe.NAME == 'bobby'),lit('200000'))\
                           .otherwise(lit('150000'))).show()

+---+-------+---------+------+
| ID|   NAME|  Company|Salary|
+---+-------+---------+------+
|  1| sravan|company 1|100000|
|  2| ojaswi|company 1|100000|
|  3| rohith|company 2|100000|
|  4|sridevi|company 1|100000|
|  5|  bobby|company 1|100000|
+---+-------+---------+------+

In [2]:
# Adding multiple columns into dataframe

# Using withcolumn

# importing module
import pyspark

# import concat_ws and lit function
from pyspark.sql.functions import concat_ws, lit

# importing sparksession from pyspark.sql module
from pyspark.sql import SparkSession

# creating sparksession and giving an app name
spark = SparkSession.builder.appName('sparkdf').getOrCreate()

# list  of employee data
data = [["1", "sravan", "company 1"],
        ["2", "ojaswi", "company 1"],
        ["3", "rohith", "company 2"],
        ["4", "sridevi", "company 1"],
        ["5", "bobby", "company 1"]]

# specify column names
columns = ['ID', 'NAME', 'Company']

# creating a dataframe from the lists of data
dataframe = spark.createDataFrame(data, columns)

dataframe.withColumn("new_col1", lit("new")).withColumn("new_col2", lit("new2")).show()

+---+-------+---------+--------+--------+
| ID|   NAME|  Company|new_col1|new_col2|
+---+-------+---------+--------+--------+
|  1| sravan|company 1|     new|    new2|
|  2| ojaswi|company 1|     new|    new2|
|  3| rohith|company 2|     new|    new2|
|  4|sridevi|company 1|     new|    new2|
|  5|  bobby|company 1|     new|    new2|
+---+-------+---------+--------+--------+

In [3]:
# Using select function

dataframe.select('*',lit("new1").alias("new1"),lit("new2").alias("new2")).show()

+---+-------+---------+----+----+
| ID|   NAME|  Company|new1|new2|
+---+-------+---------+----+----+
|  1| sravan|company 1|new1|new2|
|  2| ojaswi|company 1|new1|new2|
|  3| rohith|company 2|new1|new2|
|  4|sridevi|company 1|new1|new2|
|  5|  bobby|company 1|new1|new2|
+---+-------+---------+----+----+

In [4]:
# Using both select and withColumn

dataframe.select('*',lit("new1").alias("new1"),lit("new2").alias("new2")).withColumn("new3",lit(3)).show()

+---+-------+---------+----+----+----+
| ID|   NAME|  Company|new1|new2|new3|
+---+-------+---------+----+----+----+
|  1| sravan|company 1|new1|new2|   3|
|  2| ojaswi|company 1|new1|new2|   3|
|  3| rohith|company 2|new1|new2|   3|
|  4|sridevi|company 1|new1|new2|   3|
|  5|  bobby|company 1|new1|new2|   3|
+---+-------+---------+----+----+----+